### PR TITLE
Searchable Phrases & Roots in Latin & English

### PR DESCRIPTION
**Pull request by shadoath**
Tried to do a fancy rebase and caused some merge issues. 
Anyway, when you can look at it feel free to add styling it's not my strong suit (yet).

### CODE REVIEW

**Comment by jbendercode** [comment]
Will try to merge sometime this week/weekend and update the extension. Thank you for the contributions.

**Comment by jbendercode** [comment]
Hi Shadoath, thanks again for the contributions. Feel free to fork this repo and do whichever work you would like on it. Unfortunately the styling does not align that well with the current release on Chrome extensions. I have merged the changes but I don't have the capacity right now to update the styling. I may have some time in the future, I am swamped right now though. If you would like to submit a styling update, I can review it and possibly push it up. Cheers, Josh!

**Comment by shadoath** [comment]
@jbendercode 	What styling does not align well? 
Point me in the right direction and I will get it updated.

If you are feeling swamped right now with updates and would like to extend ownership of this extension to me I am happy to help maintain it.

**Comment by jbendercode** [comment]
Hi Skylar,

I should have some time this week to take a closer look at it. Sorry that I
let this slip by the wayside. I really appreciate your effort on the
project. Will get back to you soon.

Thanks,
Josh

**Pull request merged**
